const Products = [
  {
    id: 1,
    name: "White tshirt",
    image: "/images/productTabImage1.jpeg",
    price: "100",
    description: "Description for Product 1",
    type: "Men",
    sizes: ["XS", "S", "M"],
    color: "White",
  },
  {
    id: 2,
    name: "Trench coat",
    image: "/images/productTabImage2.jpeg",
    price: "150",
    description: "Description for Product 2",
    type: "Men",
    sizes: ["XS", "S", "M", "XXL"],
    color: "Black",
  },
  {
    id: 3,
    name: "Yellow Hodiee",
    image: "/images/productTabImage3.webp",
    price: "150",
    description: "Description for Product 2",
    type: "Men",
    sizes: ["XS", "S", "M"],
    color: "Yellow",
  },
  {
    id: 4,
    name: "Denim jacket",
    image: "/images/productTabImage4.webp",
    price: "150",
    description: "Description for Product 2",
    type: "Men",
    sizes: ["S", "M"],
    color: "Blue",
  },
  {
    id: 5,
    name: "Red leather jacket",
    image: "/images/productTabImage5.webp",
    price: "150",
    description: "Description for Product 2",
    type: "Men",
    sizes: ["S", "M"],
    color: "Red",
  },
  {
    id: 6,
    name: "White sweater  ",
    image: "/images/productTabImage6.webp",
    price: "150",
    description: "Description for Product 2",
    type: "Men",
    sizes: ["XS", "S", "M"],
    color: "White",
  },
  {
    id: 7,
    name: "Oversize tshirt",
    image: "/images/productTabImage7.webp",
    price: "150",
    description: "Description for Product 2",
    type: "Men",
    sizes: ["S"],
    color: "Black",
  },

  {
    id: 8,
    name: "Denim jeans",
    image: "/images/productTabImage8.jpeg",
    price: "150",
    description: "Description for Product 2",
    type: "Men",
    sizes: ["XS", "S", "M"],
    color: "Blue",
  },
  {
    id: 9,
    name: "Denim jacket",
    image: "/images/productTabImage9.webp",
    price: "150",
    description: "Description for Product 2",
    type: "Men",
    sizes: ["XS", "S", "M"],
    color: "Blue",
  },
  {
    id: 10,
    name: "Yellow Hoodie",
    image: "/images/productTabImage1.jpeg",
    price: "150",
    description: "Description for Product 1",
    type: "Women",
    sizes: ["XS", "S", "M", "XL", "XXL"],
    color: "Blue",
  },
  {
    id: 11,
    name: "Green Hodiee",
    image: "/images/productTabImage2.jpeg",
    price: "150",
    description: "Description for Product 2",
    type: "Women",
    sizes: ["XS", "S", "M"],
    color: "Blue",
  },
  {
    id: 12,
    name: "Red Hodiee",
    image: "/images/productTabImage3.webp",
    price: "150",
    description: "Description for Product 2",
    type: "Women",
    sizes: ["XS", "S", "M"],
    color: "Blue",
  },
  {
    id: 13,
    name: "Olive Hodiee",
    image: "/images/productTabImage4.webp",
    price: "150",
    description: "Description for Product 2",
    type: "Women",
    sizes: ["S", "M"],
    color: "Blue",
  },
  {
    id: 14,
    name: "White Hodiee",
    image: "/images/productTabImage5.webp",
    price: "150",
    description: "Description for Product 2",
    type: "Women",
    sizes: ["XS", "S", "M"],
    color: "Blue",
  },
  {
    id: 15,
    name: "White Hodiee",
    image: "/images/productTabImage6.webp",
    price: "150",
    description: "Description for Product 2",
    type: "Women",
    sizes: ["XS", "S", "M"],
    color: "Blue",
  },
  {
    id: 16,
    name: "White Hodiee",
    image: "/images/productTabImage7.webp",
    price: "150",
    description: "Description for Product 2",
    type: "Women",
    sizes: ["XS", "S", "M"],
    color: "Blue",
  },

  {
    id: 17,
    name: "White Hodiee",
    image: "/images/productTabImage8.jpeg",
    price: "150",
    description: "Description for Product 2",
    type: "Women",
    sizes: ["XS", "S"],
    color: "Blue",
  },
  {
    id: 18,
    name: "White Hodiee",
    image: "/images/productTabImage9.webp",
    price: "150",
    description: "Description for Product 2",
    type: "Women",
    sizes: ["XS", "S", "M"],
    color: "Blue",
  },
  {
    id: 19,
    name: "Gold & Silver necklace",
    image: "/images/jewellery-picture.webp",
    price: "100",
    description: "Description for Product 1",
    type: "Jewellery",
    sizes: ["XS", "S", "M"],
  },
  {
    id: 20,
    name: "Silver necklace",
    image: "/images/jewellery-picture0.jpeg",
    price: "150",
    description: "Description for Product 2",
    type: "Jewellery",
    sizes: ["XS", "S", "M"],
  },
  {
    id: 21,
    name: "Silver jewellery set",
    image: "/images/jewellery-picture1.webp",
    price: "80",
    description: "Description for Product 2",
    type: "Jewellery",
    sizes: ["XS", "S", "M"],
  },
  {
    id: 22,
    name: "Silver bracelet",
    image: "/images/jewellery-picture2.webp",
    price: "300",
    description: "Description for Product 2",
    type: "Jewellery",
    sizes: ["XS", "S", "M"],
  },
  {
    id: 23,
    name: "Brace jewellery  set",
    image: "/images/jewellery-picture3.webp",
    price: "58",
    description: "Description for Product 2",
    type: "Jewellery",
    sizes: ["XS", "M"],
  },
  {
    id: 24,
    name: "Silver Verj jewellery winter set",
    image: "/images/JewelleryImages/jewellery-picture4.webp",
    price: "150",
    description: "Description for Product 2",
    type: "Jewellery",
    sizes: ["XS", "S"],
  },
  {
    id: 25,
    name: "Ave Sunglasses",
    image: "/images/jewellery-picture5.webp",
    price: "299",
    description: "Description for Product 2",
    type: "Jewellery",
    sizes: ["XS", "S", "M"],
  },
  {
    id: 26,
    name: "White gold necklace",
    image: "/images/jewellery-picture6.webp",
    price: "1250",
    description: "Description for Product 2",
    type: "Jewellery",
    sizes: ["XS", "S", "M"],
  },

  {
    id: 27,
    name: "Golden face jewellery",
    image: "/images/jewellery-picture8.jpeg",
    price: "580",
    description: "Description for Product 2",
    type: "Jewellery",
    sizes: ["XS", "S"],
  },

  // Add more products here
];

export { Products };
